# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0a278283ffe1e85afc1aa6e1be4b950ccb2ecc1186c05952bbaceafd5a2b2eb935e8ed7093d6fd995702342d345f31b14f668935eb6645272c825a6fac282ad

test:
  secret_key_base: 99165fa9759c2955124a3e90f6305b7a99d94bf8e0e98bb2d7168e2346f28ffbb00eb51abdbb5b464993b980586485f207bf128ac8a77c5ffbafeec36fbb5a42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
